#index:
#    path: /
#    controller: App\Controller\DefaultController::index

articles:
    path:     /articles
    controller: App\Controller\ArticlesController::getArticles

article:
    path: /article/{id}
    controller: App\Controller\ArticlesController::getArticle
