version: '3.3'

services:

#Web-server
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend:/var/www
      - ./env/nginx/conf.d:/etc/nginx/conf.d
    links:
      - php
    networks:
      - app-network

#Applications
  php:
    container_name: php
    build: ./backend
    restart: unless-stopped
    tty: true
    expose:
      - "9000"
    links:
      - mysql
    volumes:
      - ./backend:/var/www/
    networks:
      - app-network

  react-blog:
    container_name: react-blog
    build: ./blog-front
    ports:
      - "3000:3000"
    volumes:
      - ./blog-front:/var/www
      - /var/www/node_modules
    environment:
      TZ: 'Europe/Kiev'
    stdin_open: true

  react-admin:
    container_name: react-admin
    build: ./admin-front
    ports:
      - "3001:3000"
    volumes:
      - ./admin-front:/var/www
      - /var/www/node_modules
    environment:
      TZ: 'Europe/Kiev'
    stdin_open: true

#Database
  mysql:
    container_name: mysql
    restart: always
    image: mysql:5.7
    ports:
      - "3306:3306"
    tty: true
    volumes:
      - ./env/mysql:/var/lib/mysql
    environment:
      TZ: 'Europe/Kiev'
      MYSQL_DATABASE: 'blog'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge